### ISSUE TITLE
icon for The Quize App

### ISSUE THREAD

**Issue by hafizahmmed** [ahadali/TheQuizApp#1]
Hello,
Good Day, i make a logo icon for your project.Because there is no logo in your project. If you want to use this icon in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change.

![quzapp-01](https://user-images.githubusercontent.com/38810169/39988710-e26babe0-5789-11e8-92e4-af839d62fc8f.png)

**Comment by ahadali** [comment]
Hello @hafizahmmed this logo seems nice to me 🙂. You can share your source file.

**Comment by hafizahmmed** [comment]
Ok   please check #2

**Comment by hafizahmmed** [comment]
please check #2

and

source file here https://drive.google.com/open?id=1N9otgg9fKw38uNfop0nA25Ngimq2b73F
